numero = input('digite um numero: ')
n = str(numero)
print('analisando o numero {}'.format(n))
print('unidade:{}'.format(n[0]))
print('dezena:{}'.format(n[1]))
print('centena:{}'.format(n[2]))
print('milhar:{}'.format(n[3]))