frase = ('os humanos sao iguais arvores morrem ao ficarem velhos')
print(frase)
print('\n' + 'na frase aparecem {} letras a'.format(frase.count('a')))
print('\n' + 'a primeira vez que aparece a letra a è em: {}'.format(frase[:11].find('a')))
print('\n' + 'a frase aparece pela ultima vez em {}'.format(frase[14:].find('a')))